init: git config --global core.autocrlf input
shallow_clone: true
version: '{build}'
skip_tags: true
install:
  - ps: Install-Product node Stable
  - npm uninstall --save-dev @shinnn/eslint-config-node-legacy eslint istanbul istanbul-coveralls tap-spec
  - npm install
build: off
test_script: node --strong_mode test.js
